### ISSUE TITLE
Need poster for 1st May meetup

### ISSUE THREAD

**Issue by koustuvsinha** [iem-devs/awesome-mission#3]
Ashish Ranjan, Developer at EA, would interact with us and show a demo of his coding style. We would need a simple poster to put up at college premises notifying that. Open a PR with the poster creating a directory `posters` and we would decide on it.

**Comment by avikghosh** [comment]
I have created a poster for the Meetup and have created a pull request. Please go through the poster and merge the changes.

**Comment by koustuvsinha** [comment]
Done as per #4
